server:
  port: 8090
  servlet:
    context-path: "/api/v1/task-backend-services"
spring:
  application:
    name: task_management_system

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taskmanagement?serverTimezone=UTC
    name: taskmanagement

    password: ***********
    username: postgres


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true


jwt:
  secret: lYRdHOiWzUXcGXxScjHf3r7NiPopxrsUtrslYRdHOiWzUXcGXxScjHf3r7NiPopxrsUtrs

